import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import './globals.css';
import 'primeicons/primeicons.css'; // PrimeIcons CSS
import 'primereact/resources/themes/lara-light-blue/theme.css'; // Tema PrimeReact
import 'primereact/resources/primereact.min.css';
import MenuSiderBar from "@/components/MenuSiderBar"; // Core PrimeReact CSS

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased container mx-auto p-4`}
            >

                <MenuSiderBar/>
                {children}
            </body>
        </html>
    );
}
